import { useQuery } from "@tanstack/react-query";
import { useParams } from "react-router-dom";
import { Gamepad2, Loader2, AlertTriangle } from "lucide-react";
import { publicApi } from "../lib/api-client";
import { RoastReport, type Analysis } from "../components/RoastReport";
import { ScoreReport, type Comparison } from "../components/ScoreReport";

// Public, no-auth page — this is what a scanned QR opens on the visitor's device.
export function AnalysisReportPage() {
  const { id } = useParams<{ id: string }>();

  const { data, isLoading, isError } = useQuery({
    queryKey: ["analysis-report", id],
    queryFn: async () => (await publicApi.getAnalysis(id!)).data.analysis,
    enabled: !!id,
    retry: false,
  });

  // Head-to-head Score Game records carry `audit.your`; roast records don't.
  const isComparison = !!data?.audit?.your || !!data?.competitorUrl;

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-indigo-50">
      <header className="border-b border-gray-200 bg-white/80 px-4 py-4 backdrop-blur">
        <div className="mx-auto flex max-w-5xl items-center gap-2">
          <Gamepad2 className="text-indigo-600" />
          <h1 className="text-lg font-bold text-gray-900">Website Score Report</h1>
        </div>
      </header>

      <main className="mx-auto max-w-5xl px-4 py-6">
        {isLoading && (
          <div className="flex flex-col items-center gap-3 py-20 text-gray-500">
            <Loader2 className="animate-spin" /> Loading your report…
          </div>
        )}
        {(isError || (!isLoading && !data)) && (
          <div className="rounded-2xl bg-white p-8 text-center shadow-sm">
            <AlertTriangle className="mx-auto mb-3 text-amber-500" size={40} />
            <p className="text-gray-700">This report was not found or has expired.</p>
          </div>
        )}
        {data && (
          <>
            {isComparison ? (
              <ScoreReport data={data as Comparison} />
            ) : (
              <RoastReport analysis={data as Analysis} />
            )}
            <p className="mt-8 text-center text-xs text-gray-400">Generated by Rath Infotech · MMD 2026</p>
          </>
        )}
      </main>
    </div>
  );
}
